### ISSUE TITLE
#1 Business incorporation logged on blockchain

### ISSUE THREAD

**Issue by finnious** [DigitalCurrencyCompliance/DigitalCurrencyCompliance#3]

**Comment by andersonmmi** [comment]
first business recorded
https://github.com/DigitalCurrencyCompliance/DigitalCurrencyCompliance/pull/16

**Comment by andersonmmi** [comment]
company registered with PIVX
https://github.com/DigitalCurrencyCompliance/DigitalCurrencyCompliance/commit/056abc5a43de6b36f34f7807ccf5393d21ceb3ab

**Comment by andersonmmi** [comment]
Company registration completed for all data points and currencies
